name: Build and Deploy
on:
  pull_request:
    branches:
      - develop
      - 'v[0-9].[0-9].[0-9x]'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: set latest version path
        if: github.ref_name == 'develop'
        run: echo VERSIONS_PATH=/ >> $GITHUB_ENV
      - name: set old versions path
        if: github.ref_name != 'develop'
        run: echo VERSIONS_PATH=/versions/${GITHUB_REF_NAME#v}/ >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and Build
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
        run: |
          cd docs
          npm install
          npm run build